spring.application.name=imageboard

server.port=8080

# MariaDB 데이터소스 설정
spring.datasource.url=jdbc:mariadb://localhost:3306/imageboard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=human
spring.datasource.password=human
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.mvc.hiddenmethod.filter.enabled=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB
server.tomcat.max-swallow-size=50MB

# spring security default formLogin username / password
# spring.security.user.name=admin
# spring.security.user.password=Pa$$w0rd

# 업로드 파일 저장 경로 (커스텀 프로퍼티)
file.upload-dir=${user.home}/imageboard/uploads
file.thumbnail-dir=${user.home}/imageboard/thumbnails
file.allowed-extensions=jpg,jpeg,png,gif